apiVersion: v1
kind: Service
metadata:
  name: postgres-master
  namespace: default
  labels:
    app: postgres-master
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres-master