kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-master-pv-claim
  namespace: default
  labels:
    app: postgres-master
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi