apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-master
    spec:
      containers:
        - name: postgres-master
          image: anyric/postgres-master
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-master-config