apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
  namespace: default
  labels:
    app: postgres-master
data:
  POSTGRES_DB: "{{ DATABASE_NAME }}"
  POSTGRES_USER: "{{ DATABASE_USERNAME }}"
  POSTGRES_PASSWORD: "{{ DATABASE_PASSWORD }}"