- name: create a k8s cluster
  gcp_container_cluster:
    name: "db-loadbalance-cluster"
    initial_node_count: 2
    master_auth:
      username: "{{ CLUSTER_USERNAME }}"
      password: "{{ CLUSTER_PASSWORD }}"
    node_config:
      machine_type: n1-standard-1
      disk_size_gb: 500
    zone: europe-west1-b
    project: "{{ PROJECT_NAME }}"
    auth_kind: "service_account"
    service_account_file: "./account.json"
    state: present
