apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-slave
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      containers:
        - name: postgres-slave
          image: anyric/postgres-slave
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/bash", "-c", "source /app/slave_startup.sh"]
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-slave-config