apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-slave
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      containers:
        - name: postgres-slave
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-slave-config