apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-slave-config
  labels:
    app: postgres-slave
data:
  POSTGRES_DB: "{{ DATABASE_NAME }}"
  POSTGRES_USER: "{{ DATABASE_USERNAME }}"
  POSTGRES_PASSWORD: "{{ DTABASE_PASSWORD }}"