apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-slave
  labels:
    name: postgres-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgress-slave
    spec:
      containers:
        - name: postgres-slave
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-slave-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-slave-pv-claim
