kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-slave-pv-volume
  namespace: default
  labels:
    type: local
    app: postgres-slave
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
